# =============================================================================
# demo_new_model.R
#
# Step-by-step guide: finding a model on HuggingFace, handling the tokenizer,
# and running it in Rhobots.
#
# Three scenarios are covered:
#   A. Happy path  — model.safetensors + tokenizer.json  (most common)
#   B. Legacy path — pytorch_model.bin + vocab.txt only  (older BERT models)
#   C. Manual path — CUDA-saved .bin that needs conversion first
# =============================================================================

library(Rhobots)


# =============================================================================
# STEP 1: WHAT TO CHECK ON HUGGINGFACE BEFORE LOADING
# =============================================================================
#
# Before calling load_hf_bert(), open the model's Files tab on HuggingFace
# and look for:
#
#   Weights file (one of these, in order of preference):
#     model.safetensors      <- best: device-agnostic, fast, safe
#     pytorch_model.bin      <- fallback: works unless saved from a CUDA device
#
#   Tokenizer file (one of these):
#     tokenizer.json         <- best: fast HuggingFace tokenizer
#     vocab.txt              <- fallback: WordPiece, used by older BERT models
#
#   Architecture check in config.json — look for:
#     "model_type": "bert"   <- confirmed compatible
#     "architectures": ["BertModel", "BertForMaskedLM", ...]  <- compatible
#
#   Models that do NOT work (different architecture):
#     GPT-2, LLaMA, Mistral, Falcon, T5, BART — these are not BERT-family
#     and will fail to load with load_hf_bert().
#
# Tested models (all work out of the box):
#   sentence-transformers/all-MiniLM-L6-v2      -- fast general-purpose
#   allenai/scibert_scivocab_uncased             -- scientific text
#   pritamdeka/S-Scibert-snli-multinli-stsb      -- scientific sentence sim
#   anferico/bert-for-patents                    -- patent texts
#   ProsusAI/finbert                             -- financial text
#   dmis-lab/biobert-base-cased-v1.2            -- biomedical text


# =============================================================================
# SCENARIO A — Happy path: model.safetensors + tokenizer.json
# =============================================================================
# load_hf_bert() handles everything automatically.
# Downloads are cached in the hfhub cache folder (~/.cache/huggingface/hub).

enc <- load_hf_bert("sentence-transformers/all-MiniLM-L6-v2")

# Inspect what was loaded
print(enc)
# <bert_encoder>
#   repo:        sentence-transformers/all-MiniLM-L6-v2
#   hidden_size: 384
#   layers:      6
#   heads:       12
#   vocab_size:  30522
#   max_len:     512

# Quick sanity check — embed two sentences and verify cosine similarity
test_emb <- embed_texts(enc, c(
  "The sun produces energy through nuclear fusion.",
  "Solar energy is generated by nuclear reactions in the sun."
), normalize = TRUE)

# Cosine similarity = dot product for L2-normalised vectors
# These two sentences are paraphrases — similarity should be > 0.90
cos_sim <- test_emb %*% t(test_emb)
cat("Cosine similarity between paraphrases:", round(cos_sim[1, 2], 4), "\n")


# =============================================================================
# SCENARIO B — Legacy path: pytorch_model.bin + vocab.txt (no tokenizer.json)
#
# Example: allenai/scibert_scivocab_uncased
#   Files: pytorch_model.bin, vocab.txt, config.json, tokenizer_config.json
#   No tokenizer.json
# =============================================================================

enc_sci <- load_hf_bert("allenai/scibert_scivocab_uncased")
# load_hf_bert() will print:
#   Using weights file: pytorch_model.bin
#   no tokenizer.json found; falling back to WordPiece + vocab.txt
#
# This is expected. The WordPiece tokenizer (make_wordpiece_tokenizer) is
# built from vocab.txt and exposes the same interface as tok::tokenizer,
# so embed_texts() works identically.

print(enc_sci)

# If you want to inspect or reuse the tokenizer separately:
tokenizer <- enc_sci$tokenizer
encoded   <- tokenizer$encode_batch(c(
  "Neural networks learn representations from data.",
  "Deep learning models are trained on large corpora."
))
cat("Token count (sentence 1):", length(encoded[[1]]$ids), "\n")
cat("First 10 token IDs:      ", encoded[[1]]$ids[1:10], "\n")
# Token IDs starting with 101 ([CLS]) and ending with 102 ([SEP])
# are standard BERT special tokens.


# =============================================================================
# SCENARIO C — Manual path: model only has a CUDA-saved pytorch_model.bin
#
# Some older or fine-tuned models were saved from a GPU session.
# R-torch cannot deserialize these directly.
#
# Solution: convert to safetensors first, then load locally.
# =============================================================================

# --- Step C1: Convert on the HuggingFace website (no Python needed) ----------
#
# 1. Go to: https://huggingface.co/spaces/safetensors/convert
# 2. Enter the model repo ID (e.g. "some-org/my-finetuned-bert")
# 3. Click Convert. The Space creates a PR branch with model.safetensors.
# 4. Download model.safetensors from that PR branch to your local machine.

# --- Step C2: Load with a local weights_path --------------------------------

local_weights <- "/path/to/downloaded/model.safetensors"  # adjust to your path

enc_custom <- load_hf_bert(
  "some-org/my-finetuned-bert",   # still needed for config.json + tokenizer
  weights_path = local_weights
)
# load_hf_bert() will print:
#   Using provided weights file: /path/to/downloaded/model.safetensors
#
# The weights are loaded from the local file; config.json and the
# tokenizer are still fetched from the Hub.

# --- Step C3: If the tokenizer is also broken, build it manually ------------
#
# A few very old checkpoints provide neither tokenizer.json nor a clean
# vocab.txt. In that case, download vocab.txt manually and call
# make_wordpiece_tokenizer() directly.

vocab_file <- hfhub::hub_download("some-org/my-finetuned-bert", "vocab.txt")
tokenizer_manual <- make_wordpiece_tokenizer(
  vocab_path    = vocab_file,
  do_lower_case = TRUE    # set to FALSE for cased models
)

# Swap the tokenizer into an already-loaded encoder (enc_custom here):
enc_custom$tokenizer <- tokenizer_manual


# =============================================================================
# STEP 2: EMBED TEXTS
# =============================================================================
# Once the encoder is loaded (any scenario above), embed_texts() is identical.

docs <- c(
  "Photosynthesis converts sunlight into chemical energy stored in glucose.",
  "Chlorophyll absorbs light in the red and blue parts of the spectrum.",
  "Carbon dioxide and water are the raw materials for photosynthesis.",
  "International climate agreements aim to limit global warming to 1.5C.",
  "Carbon taxes create economic incentives to reduce greenhouse gas emissions.",
  "Renewable energy deployment is accelerating under net-zero commitments."
)

emb <- embed_texts(
  enc,
  docs,
  batch_size = 32,      # increase for large corpora
  max_length = 256,     # truncates tokens; 256 is fine for short abstracts
  normalize  = TRUE,    # keep TRUE for cosine-based clustering
  device     = "cpu"    # "cuda" if torch was built with CUDA support
)

cat("Embedding matrix dimensions:", nrow(emb), "x", ncol(emb), "\n")
# 6 x 384 for all-MiniLM-L6-v2


# =============================================================================
# STEP 3: CACHE THE EMBEDDINGS (important for large corpora)
# =============================================================================
# Embedding 10 000 documents can take several minutes on CPU.
# embed_texts_cached() saves to disk so you only pay once.

emb_cached <- embed_texts_cached(
  enc,
  docs,
  cache_file = "my_embeddings.rds"  # saved in working directory
)
# First call: runs the model and writes my_embeddings.rds
# Subsequent calls: loads instantly, encoder is not used

# Invalidate the cache when your docs change:
emb_recached <- embed_texts_cached(
  enc,
  docs,
  cache_file = "my_embeddings.rds",
  overwrite  = TRUE
)


# =============================================================================
# STEP 4: FIT A TOPIC MODEL
# =============================================================================

fit <- fit_bertopic(
  docs                  = docs,
  embeddings            = emb,
  hdbscan_min_pts       = 2,          # low for this tiny corpus; use 5-15 in practice
  ngram_range           = c(1L, 2L),  # include bigrams
  extra_stopwords       = c("using", "based"),
  reduce_frequent_words = TRUE,
  verbose               = FALSE
)

print(fit)
print_topics(fit)


# =============================================================================
# STEP 5: EVALUATE A SINGLE FIT
# =============================================================================
# topic_quality() computes five families of metrics on a fitted model:
#   - Silhouette   : how well-separated documents are from other topics  [↑]
#   - Cohesion     : how tightly docs cluster around their centroid       [↑]
#   - Separation   : mean cosine similarity between topic centroids       [↓]
#   - Vocab overlap: pairwise Jaccard of top-N term sets per topic       [↓]
#   - Distribution : normalised size entropy and noise ratio              [↑/↓]

q <- topic_quality(fit, top_n = 5L)
print(q)
# <topic_quality>
#   Topics: 2   Docs: 6   Noise: 0 (0.0%)
#
#   Embedding space:
#     Cohesion   (doc→centroid cos sim):     0.921  [↑ better]
#     Separation (mean inter-centroid sim):   0.411  [↓ better]
#     Silhouette score:                      0.638  [↑ better]
#   ...

# Interactive four-panel dashboard (requires plotly):
#   Panel 1 — silhouette per topic (red → green bars)
#   Panel 2 — document counts per topic + noise
#   Panel 3 — centroid similarity matrix (heatmap)
#   Panel 4 — vocabulary overlap matrix (heatmap)
visualize_quality(q, fit)


# =============================================================================
# STEP 6: EXPLORE THE PARAMETER SPACE
# =============================================================================
# sweep_topics() runs fit_bertopic + topic_quality over a full grid of
# UMAP and HDBSCAN parameters, using pre-computed embeddings so the encoder
# runs only once.  On a real corpus (thousands of documents) this is the
# fastest way to find a good combination before committing to one setting.

# --- 6A. Single encoder, sweep UMAP + HDBSCAN parameters -------------------
#
# Use a larger corpus for a meaningful sweep; the toy corpus above is too
# small for HDBSCAN to produce stable clusters across all combinations.
# Here we reuse `docs` and `emb` defined in Step 2.

sw <- sweep_topics(
  docs         = docs,
  embeddings   = emb,            # pre-computed — no re-embedding
  n_neighbors  = c(3L, 5L, 10L),
  n_components = c(3L, 5L),
  min_pts      = c(2L, 3L, 5L),
  # sample_size = 2000,          # uncomment to subsample large corpora first
  quality_top_n  = 5L,
  quality_sample = 500L,         # max docs used for silhouette calculation
  verbose = TRUE
)
# Output: one progress line per combination, e.g.
#   [1/18] encoder  n_neighbors=3   n_components=3   min_pts=2

print(sw)
# <topic_sweep>
#   Runs:    18
#   Docs:    6
#
#   Metrics (across all valid runs):
#     Silhouette:  min=0.231  median=0.512  max=0.738
#
#   Best run (highest silhouette):
#     n_neighbors: 5
#     n_components:3
#     min_pts:     2
#     n_topics:    2   silhouette: 0.738

# The best parameter combination:
sw$best

# Full results table (one row per combination + all metrics):
sw$results

# Interactive heatmap: rows = parameter combos, columns = metrics.
# Values are min-max normalised per column so green always means "best
# in that column".  Raw values are printed in each cell.  Metrics where
# lower is better (separation, Jaccard, noise %) are inverted before
# normalisation so the green/white/white direction is consistent.
visualize_sweep(sw)


# --- 6B. Compare two encoders side-by-side ----------------------------------
# Pass embeddings as a named list; sweep_topics embeds once per encoder and
# then sweeps the same UMAP/HDBSCAN grid across both.

enc2 <- load_hf_bert("Rodion/sbert_uno_sustainable_development_goals")
emb2 <- embed_texts(enc2, docs, normalize = TRUE)

sw2 <- sweep_topics(
  docs       = docs,
  embeddings = list(
    minilm = emb,    # already embedded with all-MiniLM-L6-v2
    sdg    = emb2    # SDG-specialised encoder
  ),
  n_neighbors  = c(3L, 5L),
  n_components = c(3L, 5L),
  min_pts      = c(2L, 3L),
  verbose      = TRUE
)

print(sw2)

# The heatmap now has rows like "minilm | nbr=3 cmp=3 min=2" and
# "sdg | nbr=3 cmp=3 min=2", making it easy to compare encoders
# across the same parameter settings.
visualize_sweep(sw2)

# Extract the best overall combination:
sw2$best


# =============================================================================
# TROUBLESHOOTING
# =============================================================================
#
# Error: "Could not find model weights"
#   The model has neither model.safetensors nor pytorch_model.bin.
#   Check the Files tab on HuggingFace for the actual filename and use
#   weights_path = hfhub::hub_download("repo", "actual_filename.bin")
#
# Error: "Error loading state dict" / parameter shape mismatch
#   The model is not a standard BERT architecture (e.g. it is RoBERTa, DeBERTa,
#   ELECTRA, or a custom architecture). Rhobots currently supports vanilla BERT
#   and its direct derivatives (MiniLM, MPNet on BERT base, SciBERT, etc.).
#
# Error during tokenizer load: "no tokenizer.json found"
#   This is just a warning, not an error. load_hf_bert() falls back to
#   vocab.txt automatically. If that also fails, call make_wordpiece_tokenizer()
#   manually as shown in Scenario C.
#
# Embeddings look wrong (all cosine similarities near 0 or 1)
#   Check that normalize = TRUE in embed_texts(). Without normalisation, dot
#   products are not bounded and cosine similarity must be computed manually.
#
# Model was saved on CUDA and R-torch gives a pickle error
#   See Scenario C: convert to safetensors via the HuggingFace convert Space.
