# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' HDBSCAN via Boruvka MST on mutual-reachability kNN graph
#'
#' Internal function called by \code{cluster_docs.hdbscan_clustering()}.
#' Returns a list with \code{labels} (integer vector, 0 = noise) and
#' \code{n_mst_edges} (number of MST edges built).  When \code{n_mst_edges < n-1}
#' the kNN graph was disconnected; the R wrapper retries with larger k.
#'
#' @param knn_idx Integer matrix (n x k), 1-indexed nearest-neighbour indices.
#' @param knn_dist Numeric matrix (n x k), corresponding distances.
#' @param min_pts Integer minimum cluster size / core-distance order.
#' @return Named list: \code{labels} (IntegerVector), \code{n_mst_edges} (int).
#' @keywords internal
hdbscan_boruvka_cpp <- function(knn_idx, knn_dist, min_pts) {
    .Call(`_Rhobots_hdbscan_boruvka_cpp`, knn_idx, knn_dist, min_pts)
}

#' HDBSCAN via Boruvka MST with KD-tree queries (no fixed k)
#'
#' Internal function called by \code{cluster_docs.hdbscan_clustering()} when
#' \code{knn = "kdtree"}.  Unlike \code{hdbscan_boruvka_cpp()}, this function
#' takes the raw data matrix \code{X} and builds its own KD-tree (nanoflann),
#' querying it on-demand during each Boruvka round.  No k parameter is exposed:
#' the search radius grows automatically until the MST is fully connected.
#' This replicates the behaviour of Python hdbscan's \code{boruvka_kdtree}
#' algorithm.
#'
#' @param X Numeric matrix (n x d) of point coordinates (e.g. 5-D UMAP embedding).
#' @param min_pts Integer minimum cluster size / core-distance order.
#' @return Named list: \code{labels} (IntegerVector, 0 = noise),
#'   \code{n_mst_edges} (int, always n-1 when data is connected).
#' @keywords internal
hdbscan_kdtree_cpp <- function(X, min_pts) {
    .Call(`_Rhobots_hdbscan_kdtree_cpp`, X, min_pts)
}

#' HDBSCAN via Ball-tree dual-tree Borůvka MST
#'
#' Default internal HDBSCAN implementation (called when \code{knn = "balltree"}).
#' Builds a Ball-tree from the data matrix and runs dual-tree Borůvka.  Ball
#' bounding spheres prune more effectively than axis-aligned boxes in ≥3-D,
#' keeping Borůvka rounds close to O(n log n) even on data without strong
#' cluster separation.  kNN results from the core-distance pass are reused as
#' a Borůvka warm-up, so no extra tree traversal is needed.
#'
#' @param X Numeric matrix (n x d) of point coordinates (e.g. 5-D UMAP embedding).
#' @param min_pts Integer minimum cluster size / core-distance order.
#' @return Named list: \code{labels} (IntegerVector, 0 = noise),
#'   \code{n_mst_edges} (int, always n-1 when data is connected).
#' @keywords internal
hdbscan_balltree_cpp <- function(X, min_pts) {
    .Call(`_Rhobots_hdbscan_balltree_cpp`, X, min_pts)
}

