# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' HDBSCAN via Boruvka MST on mutual-reachability kNN graph
#'
#' Internal function called by \code{cluster_docs.hdbscan_clustering()}.
#' Returns a list with \code{labels} (integer vector, 0 = noise) and
#' \code{n_mst_edges} (number of MST edges built).  When \code{n_mst_edges < n-1}
#' the kNN graph was disconnected; the R wrapper retries with larger k.
#'
#' @param knn_idx Integer matrix (n x k), 1-indexed nearest-neighbour indices.
#' @param knn_dist Numeric matrix (n x k), corresponding distances.
#' @param min_pts Integer minimum cluster size / core-distance order.
#' @return Named list: \code{labels} (IntegerVector), \code{n_mst_edges} (int).
#' @keywords internal
hdbscan_boruvka_cpp <- function(knn_idx, knn_dist, min_pts) {
    .Call(`_Rhobots_hdbscan_boruvka_cpp`, knn_idx, knn_dist, min_pts)
}

