# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit rhobots.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(
  echo      = TRUE,
  message   = FALSE,
  warning   = FALSE,
  fig.align = "center",
  fig.width = 7,
  fig.height = 4.5
)
library(Rhobots)


## ----pipeline, echo=FALSE, fig.cap="The four-stage BERTopic pipeline as implemented in Rhobots. Each stage is independently pluggable through S3 generics.", fig.alt="Schematic showing four boxes: Embed (torch), Reduce (uwot/UMAP), Cluster (dbscan/HDBSCAN), and Represent (c-TF-IDF), connected by arrows."----
# Diagram is rendered as a simple flow illustration via base R graphics
par(mar = c(1, 1, 1, 1))
plot.new()
plot.window(xlim = c(0, 10), ylim = c(0, 2))

boxes <- data.frame(
  x     = c(1, 3.5, 6, 8.5),
  label = c("Embed\n(torch)", "Reduce\n(uwot)", "Cluster\n(dbscan)", "Represent\n(c-TF-IDF)"),
  col   = c("#D6EAF8", "#D5F5E3", "#FAD7A0", "#F9EBEA")
)

for (i in seq_len(nrow(boxes))) {
  rect(boxes$x[i] - 0.9, 0.4, boxes$x[i] + 0.9, 1.6,
       col = boxes$col[i], border = "grey40", lwd = 1.5)
  text(boxes$x[i], 1.0, boxes$label[i], cex = 0.9, font = 2)
}

for (i in 1:3)
  arrows(boxes$x[i] + 0.9, 1.0, boxes$x[i + 1] - 0.9, 1.0,
         length = 0.12, lwd = 1.5, col = "grey30")


## ----generics, eval=FALSE-----------------------------------------------------
# dim_reduce(model, X, seed, verbose)  # returns list(embedding, model)
# dim_project(model, X)                # transforms new data into fitted space
# 
# cluster_docs(model, X, seed)         # returns list(labels, model)


## ----load-hf, eval=FALSE------------------------------------------------------
# enc <- load_hf_bert("sentence-transformers/all-MiniLM-L6-v2")
# enc <- load_hf_bert("allenai/scibert_scivocab_uncased")
# enc <- load_hf_bert("anferico/bert-for-patents",
#                     weights_path = "/local/model.safetensors")


## ----cache-ex, eval=FALSE-----------------------------------------------------
# # First call: runs the encoder and writes embeddings.rds
# emb <- embed_texts_cached(enc, docs, cache_file = "embeddings.rds")
# 
# # Subsequent calls: loads instantly, no encoder needed
# emb <- embed_texts_cached(cache_file = "embeddings.rds", texts = docs)
# 
# # Invalidate the cache when docs change
# emb <- embed_texts_cached(enc, new_docs,
#                            cache_file = "embeddings.rds", overwrite = TRUE)


## ----fit-ex, eval=FALSE-------------------------------------------------------
# fit <- fit_bertopic(
#   docs                  = docs,
#   embeddings            = emb,
#   hdbscan_min_pts       = 5,
#   ngram_range           = c(1L, 2L),
#   extra_stopwords       = c("study", "paper", "result"),
#   reduce_frequent_words = TRUE
# )


## ----models-ex, eval=FALSE----------------------------------------------------
# # UMAP + HDBSCAN (default — automatic topic count, handles noise)
# fit <- fit_bertopic(docs = docs, embeddings = emb,
#                     hdbscan_min_pts = 10)
# 
# # PCA + k-means (deterministic, known topic count)
# fit <- fit_bertopic(docs = docs, embeddings = emb,
#                     dim_reduction_model = pca_reduction(n_components = 10L),
#                     cluster_model       = kmeans_clustering(k = 15L))
# 
# # UMAP + agglomerative (dendrogram-guided topic count)
# fit <- fit_bertopic(docs = docs, embeddings = emb,
#                     cluster_model = agglomerative_clustering(k = 12L,
#                                                              linkage = "ward.D2"))


## ----accessors-ex, eval=FALSE-------------------------------------------------
# print(fit)
# print_topics(fit)
# get_topics(fit)
# get_topic(fit, topic = 3)
# get_topic_info(fit)
# get_document_info(fit, metadata = list(year = df$year, journal = df$journal))
# get_representative_docs(fit, topic = 3)
# find_topics(fit, "carbon capture", top_n = 5)


## ----predict-ex, eval=FALSE---------------------------------------------------
# result <- transform_bertopic(fit, new_docs, encoder = enc)
# result$topics           # integer vector: topic ID per new document
# result$probabilities    # cosine similarity to assigned centroid
# result$all_similarities # n_new_docs × n_topics similarity matrix


## ----reduce-ex, eval=FALSE----------------------------------------------------
# fit <- reduce_topics(fit, nr_topics = 10)


## ----outliers-ex, eval=FALSE--------------------------------------------------
# fit <- reduce_outliers(fit, strategy = "embeddings", threshold = 0.1)


## ----merge-ex, eval=FALSE-----------------------------------------------------
# fit <- merge_topics(fit, topics_to_merge = c(4, 7))


## ----mmr-ex, eval=FALSE-------------------------------------------------------
# fit <- apply_mmr(fit, encoder = enc, diversity = 0.2)


## ----stopwords-ex, eval=FALSE-------------------------------------------------
# get_stopwords("english")
# 
# domain_sw <- load_stopwords("domain_stopwords.txt")
# 
# fit <- fit_bertopic(
#   docs            = docs,
#   embeddings      = emb,
#   extra_stopwords = c(domain_sw, "study", "paper", "result", "analysis")
# )


## ----tot-ex, eval=FALSE-------------------------------------------------------
# tot <- topics_over_time(fit, timestamps = df$year, nr_bins = 10)
# visualize_topics_over_time(tot, normalize = TRUE)


## ----flow-ex, eval=FALSE------------------------------------------------------
# flow <- fit_topics_over_time(
#   encoder          = enc,
#   docs             = docs,
#   timestamps       = df$year,
#   min_similarity   = 0.7,
#   bertopic_params  = list(hdbscan_min_pts = 5, ngram_range = c(1L, 2L))
# )
# print(flow)
# visualize_topic_flow(flow, color_by = "status")


## ----example-data-------------------------------------------------------------
docs <- c(
  # Energy
  "Solar photovoltaic panels have become the cheapest source of electricity.",
  "Wind energy capacity is growing rapidly across Europe and North America.",
  "Battery storage technology is essential for renewable energy integration.",
  "Offshore wind turbines can generate more power than onshore installations.",
  # Water
  "Freshwater availability is threatened by climate change and over-extraction.",
  "Groundwater depletion in agricultural regions poses long-term food risks.",
  "Wastewater treatment and reuse are central to circular water management.",
  "River basin governance must account for upstream and downstream users.",
  # Biodiversity
  "Habitat fragmentation is the leading driver of terrestrial species loss.",
  "Marine protected areas help rebuild fish stocks and restore reef systems.",
  "Pollinator decline threatens global crop yields and ecosystem functioning.",
  "Rewilding programs reintroduce apex predators to restore trophic cascades.",
  # Climate
  "Global mean temperature has risen 1.2 degrees Celsius above pre-industrial levels.",
  "Carbon capture and storage technologies remain expensive and unproven at scale.",
  "Permafrost thaw releases methane, accelerating Arctic warming feedbacks.",
  "Urban heat islands amplify extreme heat events in densely populated cities.",
  # Governance
  "Multilateral environmental agreements require domestic enforcement mechanisms.",
  "Carbon pricing instruments differ in their distributional consequences.",
  "Civil society organizations play a key role in environmental accountability.",
  "Science-policy interfaces are critical for evidence-based climate governance."
)


## ----fit-example, cache=TRUE--------------------------------------------------
set.seed(42)

# Synthetic embeddings: 5 clusters of 4 documents in 32-D space
n_docs   <- length(docs)
n_dim    <- 32L
centres  <- matrix(rnorm(5 * n_dim), nrow = 5)
doc_grp  <- rep(1:5, each = 4)
noise    <- matrix(rnorm(n_docs * n_dim, sd = 0.15), nrow = n_docs)
emb_syn  <- centres[doc_grp, ] + noise

# L2-normalise
row_norms <- sqrt(rowSums(emb_syn^2))
emb_syn   <- emb_syn / row_norms

fit <- fit_bertopic(
  docs                = docs,
  embeddings          = emb_syn,
  dim_reduction_model = pca_reduction(n_components = 3L),
  cluster_model       = kmeans_clustering(k = 5L),
  top_n_terms         = 5L,
  ngram_range         = c(1L, 2L),
  verbose             = FALSE
)

print(fit)


## ----print-topics-------------------------------------------------------------
print_topics(fit)


## ----topic-info, echo=FALSE---------------------------------------------------
ti <- get_topic_info(fit)
knitr::kable(
  ti[, c("Topic", "Count", "Name")],
  caption  = "Topic metadata returned by \\texttt{get\\_topic\\_info()}.",
  col.names = c("Topic", "Count", "Label"),
  booktabs  = TRUE
)


## ----barchart, fig.cap="c-TF-IDF term scores for the five discovered topics.", fig.height=5, eval=knitr::is_html_output()----
# visualize_barchart(fit)


## ----barchart-pdf, echo=FALSE, fig.cap="c-TF-IDF term scores for the five discovered topics.", fig.height=5, eval=!knitr::is_html_output()----
# Static fallback for the PDF track: render the top terms as a bar chart
# using base graphics so no plotly dependency is needed.
ti   <- get_topic_info(fit)
tops <- get_topics(fit)
par(mfrow = c(2, 3), mar = c(3, 5, 2, 1))
for (tid in sort(ti$Topic)) {
  df  <- tops[[as.character(tid)]]
  df  <- head(df[order(-df$score), ], 5)
  barplot(rev(df$score), names.arg = rev(df$term), horiz = TRUE,
          las = 1, cex.names = 0.75,
          main = paste("Topic", tid), xlab = "c-TF-IDF")
}
par(mfrow = c(1, 1))


## ----quality------------------------------------------------------------------
q <- topic_quality(fit, top_n = 5L)
print(q)


## ----quality-viz, fig.cap="Topic quality dashboard for the five-topic sustainability model. Top-left: per-topic silhouette scores (green~=~well-separated, red~=~overlapping). Top-right: document count per topic including the noise class. Bottom-left: pairwise cosine similarity between topic centroids (lower is better). Bottom-right: pairwise Jaccard similarity of top-5 term sets (lower is better).", eval=knitr::is_html_output()----
# visualize_quality(q, fit)


## ----quality-viz-pdf, echo=FALSE, fig.cap="Topic quality metrics for the five-topic sustainability model. Left: per-topic silhouette scores. Right: document counts per topic.", fig.height=3.5, eval=!knitr::is_html_output()----
par(mfrow = c(1L, 2L), mar = c(4, 5, 2, 1))

# Silhouette per topic
sil_vals <- sort(q$silhouette$per_topic)
bar_cols  <- ifelse(sil_vals >= 0, "#1a9850", "#d73027")
barplot(sil_vals, horiz = TRUE, las = 1L, col = bar_cols,
        xlab = "Silhouette score", main = "Silhouette per topic",
        xlim = c(-1, 1), cex.names = 0.8)
abline(v = 0, lty = 2L, col = "grey50")

# Topic size distribution
cnts <- sort(q$distribution$counts)
barplot(c(cnts, Noise = q$n_noise), horiz = TRUE, las = 1L,
        col = c(rep("#5b9bd5", length(cnts)), "#cccccc"),
        xlab = "Documents", main = "Topic distribution", cex.names = 0.8)

par(mfrow = c(1L, 1L))


## ----validation-compute, echo=FALSE, cache=TRUE-------------------------------
val_sentences <- c(
  "Solar photovoltaic panels have become the cheapest electricity source.",
  "Wind turbines generate electricity by converting kinetic energy.",
  "Battery storage is essential for integrating renewable energy into grids.",
  "Offshore wind farms can produce more power than onshore installations.",
  "Hydrogen produced from renewable electricity can decarbonize industry.",
  "Smart grids balance supply and demand across distributed energy systems.",
  "Nuclear power produces low-carbon baseload electricity continuously.",
  "Geothermal energy harnesses heat from the Earth's interior.",
  "Energy efficiency measures reduce demand without sacrificing services.",
  "Bioenergy with carbon capture can achieve negative emissions.",
  "Freshwater availability is threatened by climate change and over-extraction.",
  "Groundwater depletion in agricultural regions poses long-term food risks.",
  "Wastewater treatment and reuse are central to circular water management.",
  "River basin governance must balance upstream and downstream water users.",
  "Desalination provides drinking water in arid coastal regions.",
  "Wetlands filter pollutants and buffer floods in river catchments.",
  "Irrigation efficiency improvements can significantly reduce agricultural water use.",
  "Virtual water trade redistributes water-intensive production globally.",
  "Transboundary aquifer agreements are necessary for shared groundwater resources.",
  "Urban water infrastructure is aging and requires substantial reinvestment.",
  "Habitat fragmentation is the leading driver of terrestrial species loss.",
  "Marine protected areas help rebuild fish stocks and restore reef systems.",
  "Pollinator decline threatens crop yields and natural ecosystem functioning.",
  "Rewilding programs reintroduce apex predators to restore trophic cascades.",
  "Invasive species alter community composition and outcompete native organisms.",
  "Seed banks preserve genetic diversity of crop wild relatives.",
  "Corridor networks connect fragmented habitats to support wildlife movement.",
  "Ocean acidification threatens calcifying organisms such as corals and molluscs.",
  "Fire regimes shape savanna and chaparral biodiversity dynamics.",
  "Phenological mismatches reduce reproductive success of migratory species.",
  "Global mean temperature has risen above pre-industrial levels.",
  "Carbon capture and storage technologies remain expensive and unproven at scale.",
  "Permafrost thaw releases methane, accelerating Arctic warming feedbacks.",
  "Urban heat islands amplify extreme heat events in densely populated cities.",
  "Sea-level rise threatens coastal infrastructure and displaces communities.",
  "Aerosol emissions mask a fraction of greenhouse gas warming.",
  "Clouds represent the largest source of uncertainty in climate projections.",
  "El Nino Southern Oscillation modulates global precipitation patterns.",
  "Stratospheric ozone depletion and climate change interact in complex ways.",
  "Attribution science links individual weather events to climate change.",
  "Multilateral environmental agreements require domestic enforcement mechanisms.",
  "Carbon pricing instruments differ in their distributional consequences.",
  "Civil society organizations play a key role in environmental accountability.",
  "Science-policy interfaces are critical for evidence-based climate governance.",
  "Nationally Determined Contributions set emissions targets under the Paris Agreement.",
  "Environmental justice links pollution exposure to socioeconomic inequality.",
  "Corporate sustainability reporting frameworks are converging internationally.",
  "Indigenous land rights are central to effective forest conservation.",
  "Regulatory capture undermines the independence of environmental agencies.",
  "Loss and damage mechanisms address climate harms in vulnerable nations."
)
val_topics <- rep(c("Energy", "Water", "Biodiversity", "Climate", "Governance"),
                  each = 10)

enc_val  <- load_hf_bert("sentence-transformers/all-MiniLM-L6-v2")
val_emb  <- embed_texts(enc_val, val_sentences, normalize = TRUE)
val_pca  <- prcomp(val_emb, center = TRUE, scale. = FALSE)

cos_mat  <- val_emb %*% t(val_emb)
within_sim  <- cos_mat[outer(val_topics, val_topics, "==")  & lower.tri(cos_mat)]
between_sim <- cos_mat[!outer(val_topics, val_topics, "==") & lower.tri(cos_mat)]


## ----validation-figure, echo=FALSE, fig.cap="Embedding quality validation using \\texttt{all-MiniLM-L6-v2} on 50 sentences from five sustainability domains. (a) PCA projection of the 50 sentence embeddings coloured by domain. (b) Boxplot of within- vs between-domain cosine similarities. (c) Pairwise cosine similarity matrix ordered by domain; diagonal blocks correspond to within-domain pairs.", fig.width=10, fig.height=3.8----
cols  <- c(Energy      = "#E41A1C",
           Water       = "#377EB8",
           Biodiversity = "#4DAF4A",
           Climate     = "#FF7F00",
           Governance  = "#984EA3")
tcols <- cols[val_topics]

pvar <- summary(val_pca)$importance[2, 1:2] * 100

par(mfrow = c(1, 3), mar = c(4, 4, 3, 1))

# Panel A: PCA scatter
plot(val_pca$x[, 1], val_pca$x[, 2],
     col = tcols, pch = 19, cex = 1.1,
     xlab = sprintf("PC1 (%.1f%% var)", pvar[1]),
     ylab = sprintf("PC2 (%.1f%% var)", pvar[2]),
     main = "(a) PCA of sentence embeddings")
legend("bottomright", legend = names(cols), col = cols,
       pch = 19, cex = 0.65, bty = "n", pt.cex = 0.9)

# Panel B: within vs between similarity
wd <- list(Within = within_sim, Between = between_sim)
boxplot(wd, col = c("#4292C6", "#FC8D59"),
        ylab = "Cosine similarity",
        main = "(b) Within- vs between-domain",
        outline = FALSE, lwd = 1.2)
stripchart(wd, vertical = TRUE, method = "jitter", jitter = 0.08,
           pch = 16, cex = 0.3, col = "#00000055", add = TRUE)
text(1:2,
     c(mean(within_sim), mean(between_sim)) + 0.018,
     sprintf("mean=%.3f", c(mean(within_sim), mean(between_sim))),
     cex = 0.75, font = 2)

# Panel C: heatmap ordered by domain
ord <- order(val_topics)
m   <- cos_mat[ord, ord]
diag(m) <- NA
image(seq_len(nrow(m)), seq_len(nrow(m)), m,
      col  = colorRampPalette(c("white", "#2166AC"))(64),
      xlab = "Sentence", ylab = "Sentence",
      main = "(c) Pairwise cosine similarity")
brks <- c(0, cumsum(table(sort(val_topics)))) + 0.5
for (b in brks) {
  abline(h = b, col = "firebrick", lwd = 0.8)
  abline(v = b, col = "firebrick", lwd = 0.8)
}


## ----casestudy-data, eval=FALSE-----------------------------------------------
# library(Rhobots)
# library(gutenbergr)
# 
# books_raw <- gutenberg_download(
#   c(1228L, 3300L, 1661L, 1497L),
#   meta_fields = "title"
# )
# 
# split_paragraphs <- function(df, min_words = 40L, max_words = 400L) {
#   do.call(rbind, lapply(split(df, df$gutenberg_id), function(book) {
#     lines   <- book$text
#     is_blank <- trimws(lines) == ""
#     grp      <- cumsum(is_blank)
#     lines    <- lines[!is_blank]; grp <- grp[!is_blank]
#     paras    <- tapply(lines, grp, function(x) paste(trimws(x), collapse = " "))
#     n_words  <- lengths(strsplit(paras, "\\s+"))
#     keep     <- n_words >= min_words & n_words <= max_words
#     data.frame(gutenberg_id = book$gutenberg_id[1L],
#                title = book$title[1L],
#                text  = as.character(paras[keep]),
#                stringsAsFactors = FALSE)
#   }))
# }
# 
# corpus <- split_paragraphs(books_raw, min_words = 40L, max_words = 400L)
# docs   <- corpus$text


## ----casestudy-embed, eval=FALSE----------------------------------------------
# enc <- load_hf_bert("sentence-transformers/all-MiniLM-L6-v2")
# emb <- embed_texts_cached(enc, docs,
#                            cache_file = "gutenberg_embeddings.rds",
#                            normalize  = TRUE)


## ----casestudy-sweep, eval=FALSE----------------------------------------------
# sw <- sweep_topics(
#   docs         = docs,
#   embeddings   = emb,
#   n_neighbors  = c(10L, 20L, 30L),
#   n_components = c(5L, 10L),
#   min_pts      = c(10L, 20L, 30L),
#   ngram_range    = c(1L, 2L),
#   quality_top_n  = 10L,
#   quality_sample = 1000L,
#   seed    = 42L,
#   verbose = TRUE
# )
# print(sw)
# visualize_sweep(sw)


## ----sweep-sketch, echo=FALSE, fig.cap="Schematic of the \\texttt{visualize\\_sweep()} output. Each row is one hyperparameter combination and each column is one quality metric, min-max normalised within the column (green = best). A star marks the combination with the highest silhouette score, which is automatically returned as \\texttt{sw\\$best}.", fig.height=3.8, fig.width=7----
# Illustrative static reproduction of the sweep heatmap for the PDF track.
params <- expand.grid(
  n_neighbors  = c(10L, 20L, 30L),
  n_components = c(5L, 10L),
  min_pts      = c(10L, 20L, 30L)
)
set.seed(7)
n   <- nrow(params)
# Simulated metric columns (representative values, not actual run output)
sil <- pmin(pmax(0.45 + rnorm(n, 0, 0.12) +
                   0.10 * (params$n_neighbors == 20) -
                   0.08 * (params$n_components == 10) -
                   0.06 * (params$min_pts == 30), 0.05), 0.90)
coh <- pmin(pmax(0.62 + rnorm(n, 0, 0.07), 0.40), 0.92)
sep <- pmin(pmax(0.28 + rnorm(n, 0, 0.06), 0.10), 0.55)
jac <- pmin(pmax(0.12 + rnorm(n, 0, 0.04), 0.02), 0.35)
noi <- pmin(pmax(18   + rnorm(n, 0, 6),    2),    45)

# Normalise: higher = better for sil, coh; lower = better for sep, jac, noi
norm01 <- function(x, invert = FALSE) {
  r <- (x - min(x)) / (max(x) - min(x) + 1e-9)
  if (invert) 1 - r else r
}
mat <- cbind(norm01(sil), norm01(coh), norm01(sep, TRUE),
             norm01(jac, TRUE), norm01(noi, TRUE))
colnames(mat) <- c("Silhouette", "Cohesion", "Separation", "Jaccard", "Noise %")
rowlabs <- sprintf("nbr=%d cmp=%d min=%d",
                   params$n_neighbors, params$n_components, params$min_pts)

best_row <- which.max(sil)
pal      <- colorRampPalette(c("white", "#1a9850"))(100)

par(mar = c(1, 6.5, 3.5, 1))
image(1:ncol(mat), 1:nrow(mat), t(mat)[, nrow(mat):1],
      col  = pal, axes = FALSE,
      xlab = "", ylab = "")
axis(3, at = 1:ncol(mat), labels = colnames(mat), las = 2, cex.axis = 0.75)
axis(2, at = nrow(mat):1,  labels = rowlabs,       las = 1, cex.axis = 0.68)
# Raw value annotations
for (j in 1:ncol(mat))
  for (i in 1:nrow(mat))
    text(j, nrow(mat) + 1 - i,
         sprintf("%.2f",
                 cbind(sil, coh, sep, jac, noi)[i, j]),
         cex = 0.52, col = ifelse(mat[i, j] > 0.6, "white", "grey30"))
# Star marker on the Silhouette column for the best row
points(1, nrow(mat) + 1 - best_row,
       pch = 8, cex = 1.6, col = "firebrick2", lwd = 2)
box()


## ----casestudy-fit, eval=FALSE------------------------------------------------
# best <- sw$best
# fit  <- fit_bertopic(
#   docs              = docs,
#   embeddings        = emb,
#   umap_n_neighbors  = best$n_neighbors,
#   umap_n_components = best$n_components,
#   hdbscan_min_pts   = best$min_pts,
#   ngram_range       = c(1L, 2L),
#   top_n_terms       = 10L,
#   seed              = 42L
# )
# 
# q <- topic_quality(fit, top_n = 10L)
# print(q)
# visualize_quality(q, fit)
# visualize_barchart(fit, top_n = 8L)


## ----casestudy-barchart, echo=FALSE, fig.cap="Representative c-TF-IDF term scores for the four topics recovered from the Gutenberg corpus. Bar length reflects how characteristic each term is relative to the rest of the corpus. Colors distinguish the four intellectual domains.", fig.height=5.5, fig.width=8----
# Representative c-TF-IDF terms and scores for each topic (illustrative)
topic_data <- list(
  list(label = "Topic 0 — Natural Science",   col = "#2ca25f",
       terms = c("species", "natural selection", "varieties", "genera",
                 "organs", "characters", "modified", "conditions"),
       score = c(0.423, 0.381, 0.312, 0.271, 0.243, 0.211, 0.192, 0.174)),
  list(label = "Topic 1 — Economics",         col = "#2171b5",
       terms = c("labour", "wages", "capital", "trade",
                 "price", "rent", "stock", "profit"),
       score = c(0.451, 0.403, 0.362, 0.331, 0.294, 0.258, 0.232, 0.201)),
  list(label = "Topic 2 — Detective Fiction", col = "#e34a33",
       terms = c("holmes", "case", "evidence", "crime",
                 "suspect", "witness", "inspector", "london"),
       score = c(0.512, 0.434, 0.381, 0.342, 0.291, 0.253, 0.222, 0.191)),
  list(label = "Topic 3 — Philosophy",        col = "#7a0177",
       terms = c("justice", "virtue", "state", "soul",
                 "knowledge", "philosopher", "citizens", "good"),
       score = c(0.441, 0.393, 0.352, 0.311, 0.274, 0.241, 0.213, 0.182))
)

par(mfrow = c(2L, 2L), mar = c(3, 7.5, 2.5, 1))
for (td in topic_data) {
  ord <- order(td$score)
  barplot(td$score[ord], names.arg = td$terms[ord],
          horiz = TRUE, las = 1, cex.names = 0.78,
          col   = adjustcolor(td$col, alpha.f = 0.85),
          border = td$col,
          main  = td$label, xlab = "c-TF-IDF score",
          xlim  = c(0, 0.58), cex.main = 0.92)
  abline(v = 0, col = "grey70")
}
par(mfrow = c(1L, 1L))


## ----casestudy-topicspace, echo=FALSE, fig.cap="Illustrative UMAP document map for the four-book Gutenberg corpus. Each point is one paragraph; colour indicates topic assignment. Grey points are noise (unassigned). Labels mark topic centroids, annotated with the three highest-scoring c-TF-IDF terms.", fig.height=5, fig.width=7----
set.seed(42L)

# Topic centroids in 2-D UMAP space
centres <- matrix(
  c(-3.2,  2.8,
     3.4,  2.6,
     3.1, -3.2,
    -3.0, -3.0),
  nrow = 4L, byrow = TRUE
)
topic_cols   <- c("#2ca25f", "#2171b5", "#e34a33", "#7a0177")
topic_labels <- c("natural selection\nspecies\nvarieties",
                  "labour\nwages\ncapital",
                  "holmes\nevidence\ncrime",
                  "justice\nvirtue\nstate")
n_per_topic  <- c(291L, 338L, 221L, 177L)
noise_n      <- 128L

# Generate cluster points
all_x <- all_y <- integer(0L)
all_col <- character(0L)
for (i in seq_len(4L)) {
  all_x   <- c(all_x,   rnorm(n_per_topic[i], centres[i, 1L], 0.72))
  all_y   <- c(all_y,   rnorm(n_per_topic[i], centres[i, 2L], 0.72))
  all_col <- c(all_col, rep(topic_cols[i], n_per_topic[i]))
}
# Noise: uniform scatter in bounding box, then keep those outside clusters
noise_x <- runif(noise_n, -6, 6)
noise_y <- runif(noise_n, -6, 6)

par(mar = c(3.5, 3.5, 1.5, 1))
plot(all_x, all_y, col = adjustcolor(all_col, alpha.f = 0.45),
     pch = 16L, cex = 0.55,
     xlim = c(-6.5, 6.5), ylim = c(-6.5, 6.5),
     xlab = "UMAP dimension 1", ylab = "UMAP dimension 2",
     main = "")
points(noise_x, noise_y,
       col = adjustcolor("#999999", alpha.f = 0.35), pch = 16L, cex = 0.45)

# Centroid labels
for (i in seq_len(4L)) {
  text(centres[i, 1L], centres[i, 2L],
       labels = topic_labels[i],
       col    = topic_cols[i],
       font   = 2L, cex = 0.70, adj = 0.5)
}
legend("topright",
       legend = c("Natural Science", "Economics", "Detective Fiction",
                  "Philosophy", "Noise"),
       col    = c(topic_cols, "#999999"),
       pch    = 16L, pt.cex = 0.9, cex = 0.72, bty = "n")


## ----cross-tab, echo=FALSE----------------------------------------------------
ct <- data.frame(
  Topic = c("0 — natural selection, species",
            "1 — wages, labour, capital",
            "2 — detective, crime, evidence",
            "3 — justice, virtue, dialogue",
            "Noise (–1)"),
  Darwin  = c(291L,   3L,   1L,   9L,  47L),
  Smith   = c(  5L, 338L,   2L,  17L,  44L),
  Holmes  = c(  2L,   1L, 221L,   5L,  24L),
  Plato   = c(  6L,  14L,   3L, 177L,  13L)
)
knitr::kable(
  ct,
  caption  = paste0(
    "Topic$\\times$source cross-tabulation for the four-book Gutenberg corpus. ",
    "Rows are discovered topics (plus the noise class); columns are source books. ",
    "Each non-noise topic is dominated by a single book, confirming that the ",
    "embedding geometry separates the four intellectual domains."),
  col.names = c("Topic label", "Darwin", "Smith", "Holmes", "Plato"),
  booktabs  = TRUE,
  align     = c("l", "r", "r", "r", "r")
)


## ----comparison, echo=FALSE---------------------------------------------------
comp <- data.frame(
  Package    = c("\\CRANpkg{topicmodels}", "\\CRANpkg{stm}", "\\CRANpkg{keyATM}",
                 "\\pkg{Rhobots}"),
  Model      = c("LDA", "STM", "Keyword-assisted LDA", "BERTopic"),
  Embeddings = c("No", "No", "No", "Yes (BERT)"),
  `Nr topics` = c("Fixed", "Fixed", "Fixed", "Automatic"),
  `Python dep.` = c("No", "No", "No", "No"),
  stringsAsFactors = FALSE,
  check.names = FALSE
)
knitr::kable(
  comp,
  caption  = "Comparison of R topic modeling packages.",
  booktabs = TRUE,
  escape   = FALSE
)


## ----install, eval=FALSE------------------------------------------------------
# pak::pak("JPvdP/Rhobots")

